import { TemplateConfig, TemplateType } from '@types';

export const TEMPLATES: Record<TemplateType, TemplateConfig> = {
  'modern-blue': {
    name: 'Modern Blue',
    id: 'modern-blue',
    description: 'Clean, professional template with blue accent color',
    isPremium: false,
    colors: {
      primary: '#1e40af',
      secondary: '#f3f4f6',
      accent: '#3b82f6',
      text: '#1f2937',
      background: '#ffffff',
    },
    layout: {
      columnLayout: '2-col',
      headerStyle: 'full-width',
      spacing: 'normal',
    },
  },
  executive: {
    name: 'Executive',
    id: 'executive',
    description: 'Premium executive template with sidebar',
    isPremium: true,
    colors: {
      primary: '#1a1a1a',
      secondary: '#f5f5f5',
      accent: '#d97706',
      text: '#2d2d2d',
      background: '#ffffff',
    },
    layout: {
      columnLayout: '2-col',
      headerStyle: 'sidebar',
      spacing: 'spacious',
    },
  },
  minimalist: {
    name: 'Minimalist',
    id: 'minimalist',
    description: 'Ultra-clean, ATS-friendly minimalist design',
    isPremium: false,
    colors: {
      primary: '#000000',
      secondary: '#f9fafb',
      accent: '#666666',
      text: '#1f2937',
      background: '#ffffff',
    },
    layout: {
      columnLayout: '1-col',
      headerStyle: 'minimal',
      spacing: 'compact',
    },
  },
  creative: {
    name: 'Creative',
    id: 'creative',
    description: 'Bold, creative template for designers and marketers',
    isPremium: true,
    colors: {
      primary: '#ec4899',
      secondary: '#fce7f3',
      accent: '#f97316',
      text: '#1f2937',
      background: '#ffffff',
    },
    layout: {
      columnLayout: '2-col',
      headerStyle: 'full-width',
      spacing: 'spacious',
    },
  },
  classic: {
    name: 'Classic',
    id: 'classic',
    description: 'Timeless traditional resume template',
    isPremium: false,
    colors: {
      primary: '#2c3e50',
      secondary: '#ecf0f1',
      accent: '#3498db',
      text: '#2c3e50',
      background: '#ffffff',
    },
    layout: {
      columnLayout: '1-col',
      headerStyle: 'full-width',
      spacing: 'normal',
    },
  },
  tech: {
    name: 'Tech',
    id: 'tech',
    description: 'Modern tech-focused template with code-like styling',
    isPremium: true,
    colors: {
      primary: '#0f172a',
      secondary: '#e2e8f0',
      accent: '#06b6d4',
      text: '#1e293b',
      background: '#ffffff',
    },
    layout: {
      columnLayout: '2-col',
      headerStyle: 'full-width',
      spacing: 'compact',
    },
  },
  'modern-minimal': {
    name: 'Modern Minimal',
    id: 'modern-minimal',
    description: 'Contemporary minimal design with accent color',
    isPremium: true,
    colors: {
      primary: '#475569',
      secondary: '#f1f5f9',
      accent: '#8b5cf6',
      text: '#1e293b',
      background: '#ffffff',
    },
    layout: {
      columnLayout: '2-col',
      headerStyle: 'full-width',
      spacing: 'normal',
    },
  },
  'ats-optimized': {
    name: 'ATS Optimized',
    id: 'ats-optimized',
    description: 'Specifically designed to pass ATS systems with perfect formatting',
    isPremium: false,
    colors: {
      primary: '#000000',
      secondary: '#ffffff',
      accent: '#000000',
      text: '#000000',
      background: '#ffffff',
    },
    layout: {
      columnLayout: '1-col',
      headerStyle: 'minimal',
      spacing: 'compact',
    },
  },
  harvard: {
    name: 'Harvard',
    id: 'harvard',
    description: 'Classic Ivy League format',
    isPremium: true,
    colors: {
      primary: '#A51C30',
      secondary: '#f9fafb',
      accent: '#1e293b',
      text: '#111827',
      background: '#ffffff',
    },
    layout: {
      columnLayout: '1-col',
      headerStyle: 'full-width',
      spacing: 'normal',
    },
  },
  startup: {
    name: 'Startup',
    id: 'startup',
    description: 'Bold & Modern for tech',
    isPremium: true,
    colors: {
      primary: '#6366f1',
      secondary: '#eef2ff',
      accent: '#4f46e5',
      text: '#1f2937',
      background: '#ffffff',
    },
    layout: {
      columnLayout: '2-col',
      headerStyle: 'full-width',
      spacing: 'normal',
    },
  },
  corporate: {
    name: 'Corporate',
    id: 'corporate',
    description: 'Traditional & Reliable',
    isPremium: true,
    colors: {
      primary: '#0f172a',
      secondary: '#f1f5f9',
      accent: '#334155',
      text: '#0f172a',
      background: '#ffffff',
    },
    layout: {
      columnLayout: '1-col',
      headerStyle: 'minimal',
      spacing: 'spacious',
    },
  },
  elegant: {
    name: 'Elegant',
    id: 'elegant',
    description: 'Refined & Sophisticated',
    isPremium: true,
    colors: {
      primary: '#9d174d',
      secondary: '#fdf2f8',
      accent: '#be185d',
      text: '#4c1d95',
      background: '#ffffff',
    },
    layout: {
      columnLayout: '2-col',
      headerStyle: 'sidebar',
      spacing: 'spacious',
    },
  },
  developer: {
    name: 'Developer',
    id: 'developer',
    description: 'Clean Monospace aesthetics',
    isPremium: true,
    colors: {
      primary: '#10b981',
      secondary: '#ecfdf5',
      accent: '#059669',
      text: '#064e3b',
      background: '#ffffff',
    },
    layout: {
      columnLayout: '1-col',
      headerStyle: 'minimal',
      spacing: 'compact',
    },
  },
};

export default TEMPLATES;
